#!/bin/bash

set -e

BOOKMARKS=$QUTE_CONFIG_DIR/bookmarks/urls
TMPFILE=$(mktemp)
trap 'rm -f "$TMPFILE"' EXIT

cp "$BOOKMARKS" "$TMPFILE"

emacsclient -c "$TMPFILE"

removed=$(comm -23 <(sort "$BOOKMARKS") <(sort "$TMPFILE"))
added=$(comm   -13 <(sort "$BOOKMARKS") <(sort "$TMPFILE"))

if [[ -z $removed && -z $added ]]; then
    echo message-info '"did not change anything"' > "$QUTE_FIFO"
else
    while IFS=' ' read -r url title && [[ -n $url ]]; do
        echo bookmark-del "$url" > "$QUTE_FIFO"
    done <<< "$removed"

    while IFS=' ' read -r url title && [[ -n $url ]]; do
        echo bookmark-add "$url" "\"$title\"" > "$QUTE_FIFO"
    done <<< "$added"
fi

