#!/bin/bash

temp="$(mktemp)"

trap 'rm -f $temp' EXIT

ranger --choosedir "$temp" --cmd="cd $HOME/Downloads"

content="$(cat "$temp" 2>/dev/null)" &&
    if [[ "$content" ]]; then
        cd "$content"; exec zsh
    fi

