#!/bin/sh

if [ "$1" = replay ]; then
    exec rememberer --replay
else
    jsfile=$HOME/.local/share/rememberer/.last_js
    if [ "$1" = nosave ]; then
        rememberer --quiet --everything --no-remember "$QUTE_URL" < "$QUTE_HTML"
    else
        rememberer "$QUTE_URL" < "$QUTE_HTML"
    fi
    echo "jseval -q -f $jsfile" > "$QUTE_FIFO"
fi
