#!/bin/sh

if [ "$1" = replay ]; then
    exec rememberer --replay
elif [ "$1" = replayother ]; then
    exec rememberer --replay-other
else
    js=/tmp/rememberer_mark
    rm -f "$js"
    rememberer --mark "$js" "$QUTE_URL" < "$QUTE_HTML"
    echo "jseval -q -f $js" > "$QUTE_FIFO"
fi
