#!/bin/sh

if [ -z "$1" ] && command -v rememberer >/dev/null 2>&1; then
    rememberer --test "$QUTE_URL" < "$QUTE_HTML"
    status=$?
    if [ $status -eq 0 ]; then
        echo "$QUTE_URL" >> /tmp/qute_save_url
        echo message-info "'saved $QUTE_URL'" > "$QUTE_FIFO"
    elif [ $status -eq 1 ]; then
        echo message-info "'seen before'" > "$QUTE_FIFO"
    else
        exit 1
    fi
else
    echo "$QUTE_URL" >> /tmp/qute_save_url
    echo message-info "'saved $QUTE_URL'" > "$QUTE_FIFO"
fi
