#!/bin/sh

rememberer=
if [ "$1" = --rememberer ]; then
    rememberer=t
    shift
fi

suffix=
suffixmsg=
if [ -n "$1" ]; then
    suffix=$1
    suffixmsg=" to suffix $suffix"
fi

file=/tmp/qute_save_url$suffix

if [ -n "$rememberer" ] && command -v rememberer >/dev/null 2>&1; then
    rememberer --test "$QUTE_URL" < "$QUTE_HTML"
    status=$?
    if [ $status -eq 0 ]; then
        echo "$QUTE_URL" >> "$file"
        echo message-info "'saved $QUTE_URL$suffixmsg'" > "$QUTE_FIFO"
    elif [ $status -eq 1 ]; then
        echo message-info "'seen before'" > "$QUTE_FIFO"
    else
        exit 1
    fi
else
    echo "$QUTE_URL" >> "$file"
    echo message-info "'saved $QUTE_URL$suffixmsg'" > "$QUTE_FIFO"
fi
