#!/bin/sh

engine=$(sed -n '/^go/ { s/^go //; s/{}$//; p }' < "$QUTE_CONFIG_DIR/engines")

echo "$QUTE_URL" | sed -En \
's|^.*q=([^&]+).*$|open '"$engine"'\1|
T fail
p
b
: fail
c message-warning "only werkz on duckduckgo"
p' > "$QUTE_FIFO"
