#!/bin/bash

set -e

LATESTFILE=/tmp/quterorrentdownloadlatest

path=$( ( [[ -f $LATESTFILE ]] && cat "$LATESTFILE"; jq -r '.download_location_paths_list[]?' "$HOME/.config/deluge/core.conf"; echo other ) | fzf_dmenu --prompt="Download: ")

if [[ $path = other ]]; then
    echo message-info "'Starting graphical deluge'" > "$QUTE_FIFO"
    deluge-gtk "$QUTE_URL"
elif [[ -n $path ]]; then
    if [[ $path = latest:* ]]; then
        path=${path#latest:}
    else
        name=$(cd "$path"; fzf_dmenu -- -p 'subfolder: ' -i .)
        if [[ -n $name ]]; then
            path=$(realpath "$path/$name")
            if [[ -e $path && ! -d $path ]]; then
                echo message-error "'Path exists and is not a directory, aborting'" > "$QUTE_FIFO"
                exit
            fi
            if [[ ! -d $path ]]; then
                mkdir "$path"
            fi
        else
            echo message-error "'Aborted'" > "$QUTE_FIFO"
            exit
        fi
    fi

    if pgrep -x deluged &>/dev/null; then
        echo message-info "'Starting deluge-console...'" > "$QUTE_FIFO"
        if ! console_out=$(deluge-console "add -p \"$path\" \"$QUTE_URL\""); then
            if grep -xqF 'Torrent added!' <<< "$console_out"; then
                echo message-warning "'deluge-console failed but seems to have worked anyway'" > "$QUTE_FIFO"
            else
                echo message-error "'deluge-console failed, aborting...'" > "$QUTE_FIFO"
                exit 1
            fi
        fi
        echo message-info "'...added'" > "$QUTE_FIFO"
        echo "latest:$path" > "$LATESTFILE"
    else
        echo message-error "'deluged is not running, aborting...'" > "$QUTE_FIFO"
    fi
else
    echo message-error "'Aborted'" > "$QUTE_FIFO"
fi
