#!/bin/bash

set -e

[[ -z $DLDIR ]] && DLDIR=$HOME/Videos/yt
declare -p YTDLFLAGS &>/dev/null || YTDLFLAGS=(--merge-output-format mkv --write-thumbnail --no-playlist)

cookies=
domain=.youtube.com
if [[ "$QUTE_URL" = *"$domain"* ]]; then
    tmp=$(mktemp --tmpdir 'ytdl.XXXXXX')
    trap "rm -f '$tmp'" EXIT
    if "$QUTE_CONFIG_DIR/userscripts/print_cookies" "$QUTE_DATA_DIR/webengine/Cookies" "$domain" > "$tmp"; then
        cookies=$tmp
        echo "message-info 'Passing cookies to youtube-dl'" >> "$QUTE_FIFO"
    else
        echo "message-warning 'Couldnt pass cookies, ignoring...'" >> "$QUTE_FIFO"
    fi
fi

yt_prog=youtube-dl
if command -v youtube-dl-format &>/dev/null; then
    yt_prog=youtube-dl-format
else
    echo "message-warning 'Could not find youtube-dl-format, using the normal one'" >> "$QUTE_FIFO"
fi

cd "$DLDIR"
echo "message-info 'starting download of $QUTE_URL'" > "$QUTE_FIFO"
if $yt_prog ${cookies:+ --cookies "$cookies"} "${YTDLFLAGS[@]}" "$QUTE_URL"; then
    echo "message-info 'downloaded successfully to $DLDIR'" > "$QUTE_FIFO"
else
    echo "message-error 'download failed'" > "$QUTE_FIFO"
fi
